[package]
name = "red_pandas"
version = "0.1.1"
authors = ["Ricardo Marmolejo García <makiolo@gmail.com>"]
edition = "2021"
crate-type = ["staticlib"]
# links = "red_pandas_static"

[build-dependencies]
cc = "1.0"
cmake = "0.1"
cbindgen = "0.24.0"

