[package]
name = "rust_cpp"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
http_parser = "0.0.2"

[dependencies.test_cpp]
path = "./test_cpp"
version = "0.1.0"
