site_name: Mercury
docs_dir: input
site_dir: output
theme:
    name: material
    palette:
      primary: red
    custom_dir: input/theme
    features:
      - content.code.annotate
site_url: ""
use_directory_urls: false
markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.keys
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - abbr
plugins:
    - search
    - localsearch
    - print-site
extra_javascript:
    - javascripts/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
    - "Welcome": 'index.md'
    - "Install": 'install.md'
    - "About": 'about.md'

