name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: anaconda-client-env
        # environment-file: etc/example-environment.yml
        auto-activate-base: true
    - run: |
        conda install numpy
        conda install -c intel mkl mkl-devel
        conda install -c anaconda boost
        conda info
        conda list
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run Test
      run: cargo test --verbose
